# Generated by Django 2.2 on 2020-09-19 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Contact',
            new_name='CContact',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Name',
            new_name='CName',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Profile_Image',
            new_name='CProfile_Image',
        ),
        migrations.RenameField(
            model_name='vendors',
            old_name='Contact',
            new_name='VContact',
        ),
        migrations.RenameField(
            model_name='vendors',
            old_name='Name',
            new_name='VName',
        ),
        migrations.RenameField(
            model_name='vendors',
            old_name='Profile_Image',
            new_name='VProfile_Image',
        ),
    ]
