# Generated by Django 2.2 on 2020-09-20 04:35

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0004_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='ndetails',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='News Details'),
        ),
        migrations.AlterField(
            model_name='news',
            name='ntitle',
            field=models.CharField(default='NSU Garment System', max_length=500, verbose_name='News Title'),
        ),
    ]
