# Generated by Django 2.2 on 2020-09-21 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pos', '0002_product_price_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorsCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(blank=True, max_length=200, verbose_name='Instituion Name')),
                ('institution_id', models.CharField(blank=True, max_length=200, verbose_name='Instituion ID')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='Address')),
                ('contact', models.CharField(blank=True, default='N/A', max_length=20, verbose_name='Contact')),
                ('profile_Image', models.ImageField(blank=True, default='https://icon-library.net/images/young-person-icon/young-person-icon-7.jpg', upload_to='Vendor_Customer_Profile_Pic/', verbose_name='Profile Image')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=2, verbose_name='Gender')),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Updated_at', models.DateTimeField(auto_now=True)),
                ('user', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
