# Generated by Django 2.2.4 on 2020-09-19 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sales_Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(blank=True, max_length=11, null=True)),
                ('product_name', models.CharField(blank=True, max_length=11, null=True)),
                ('product_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('product_picture', models.ImageField(upload_to='image/')),
                ('product_colour', models.CharField(blank=True, max_length=11, null=True)),
                ('description', models.TextField()),
                ('deliverd', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_recived', models.CharField(choices=[('D', 'Done'), ('P', 'Pending')], default='D', max_length=2)),
                ('raw_materials_collection', models.CharField(choices=[('D', 'Done'), ('P', 'Pending')], default='D', max_length=2)),
                ('production_stage1', models.CharField(choices=[('D', 'Done'), ('P', 'Pending')], default='D', max_length=2)),
                ('production_stage2', models.CharField(choices=[('D', 'Done'), ('P', 'Pending')], default='D', max_length=2)),
                ('packing', models.CharField(choices=[('D', 'Done'), ('P', 'Pending')], default='D', max_length=2)),
                ('shipping', models.CharField(choices=[('D', 'Done'), ('P', 'Pending')], default='D', max_length=2)),
                ('sales_manager', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='procurement.Sales_Manager')),
            ],
        ),
    ]
