# Generated by Django 2.2 on 2020-09-20 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_auto_20200920_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_status',
            name='sales_manager',
        ),
    ]
