# Generated by Django 2.2 on 2020-09-20 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_remove_order_status_sales_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_status',
            name='sales_manager',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='procurement.Sales_Manager'),
        ),
    ]
