# Generated by Django 2.2 on 2020-09-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20200921_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bill Name or Code'),
        ),
        migrations.AlterField(
            model_name='completed_order',
            name='order_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Order Name or Code'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Payment Name or Code'),
        ),
    ]
